name: Set up cache
description: Set up the buildsystem cache for faster consecutive builds.

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.scons-cache/
        key: ${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}-${{ env.GIT_BASE_REF }}-${{ github.ref }}-${{ github.sha }}

        # We try to match an existing cache to restore from it. Each potential key is checked against
        # all existing caches as a prefix. E.g. 'windows-x86_64' would match any cache that starts with
        # "windows-x86_64", such as "windows-x86_64-master-refs/heads/master-6588a4a29af1621086feac0117d5d4d37af957fd".
        #
        # We check these prefixes in this order:
        #
        #   1. The exact match, including the base branch, the commit reference, and the SHA hash of the commit.
        #   2. A partial match for the same base branch and the same commit reference.
        #   3. A partial match for the same base branch and the base branch commit reference.
        #   4. A partial match for the same base branch only (not ideal, matches any PR with the same base branch).

        restore-keys: |
          ${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}-${{ env.GIT_BASE_REF }}-${{ github.ref }}-${{ github.sha }}
          ${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}-${{ env.GIT_BASE_REF }}-${{ github.ref }}
          ${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}-${{ env.GIT_BASE_REF }}-refs/heads/${{ env.GIT_BASE_REF }}
          ${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}-${{ env.GIT_BASE_REF }}
