name: Install build dependencies
description: Set up python, install the pip version of scons.

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: "3.x"

    - name: Install scons
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons==4.4.0
        scons --version

    - name: "Android: Install Java 17"
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: "Android: Install NDK"
      uses: nttld/setup-ndk@v1
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      with:
        ndk-version: r23c
        link-to-sdk: true

    - name: "Web: Install Emscripten"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.39
        actions-cache-folder: emsdk-cache
        cache-key: emsdk-${{ env.SCONS_PLATFORM }}-main

    - name: "Web: Verify Emscripten"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      shell: bash
      run: |
        emcc -v
