name: Install build dependencies
description: Install Python and SCons, platform-specific dependencies.

env:
  PYTHON_VERSION: "3.x"
  SCONS_VERSION: "4.4.0"
  JAVA_DISTRIBUTION: "temurin"
  JAVA_VERSION: "17"
  ANDROID_NDK_VERSION: "r23c"
  EMSCRIPTEN_VERSION: "3.1.39"

runs:
  using: "composite"
  steps:
    - name: Install Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install SCons ${{ env.SCONS_VERSION }}
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons==${{ env.SCONS_VERSION }}
        scons --version

    - name: "Android: Install Java ${{ env.JAVA_VERSION }}"
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: "Android: Install NDK ${{ env.ANDROID_NDK_VERSION }}"
      uses: nttld/setup-ndk@v1
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        link-to-sdk: true

    - name: "Web: Install Emscripten ${{ env.EMSCRIPTEN_VERSION }}"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ env.EMSCRIPTEN_VERSION }}
        actions-cache-folder: emsdk-cache
        cache-key: emsdk-${{ env.SCONS_PLATFORM }}-main

    - name: "Web: Verify Emscripten"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      shell: bash
      run: |
        emcc -v
