name: Install build dependencies
description: Install Python and SCons, platform-specific dependencies.

inputs:

  # These are basically local environment variables, they are NOT expected
  # to be customized by the caller.

  python_version:
    default: "3.x"
  scons_version:
    default: "4.4.0"
  java_distribution:
    default: "temurin"
  java_version:
    default: "17"
  android_ndk_version:
    default: "r23c"
  emscripten_version:
    default: "3.1.39"

runs:
  using: "composite"
  steps:
    - name: Install Python ${{ inputs.python_version }}
      uses: actions/setup-python@v5
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ inputs.python_version }}

    - name: Install SCons ${{ inputs.scons_version }}
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons==${{ inputs.scons_version }}
        scons --version

    - name: "Android: Install Java ${{ inputs.java_version }}"
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}

    - name: "Android: Install NDK ${{ inputs.android_ndk_version }}"
      uses: nttld/setup-ndk@v1
      if: ${{ env.SCONS_PLATFORM == 'android' }}
      with:
        ndk-version: ${{ inputs.android_ndk_version }}
        link-to-sdk: true

    - name: "Web: Install Emscripten ${{ inputs.emscripten_version }}"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: ${{ inputs.emscripten_version }}
        actions-cache-folder: emsdk-cache
        cache-key: emsdk-${{ env.SCONS_PLATFORM }}-main

    - name: "Web: Verify Emscripten"
      if: ${{ env.SCONS_PLATFORM == 'web' }}
      shell: bash
      run: |
        emcc -v
