name: Upload GDSiON release
description: Strip and upload build artifacts.

outputs:
  artifact-url:
    description: The URL of the uploaded artifact.
    value: ${{ steps.artifact-upload-step.outputs.artifact-url }}

runs:
  using: "composite"
  steps:
    - name: Prepare the binaries (Linux)
      if: ${{ env.SCONS_PLATFORM == 'linux' }}
      shell: bash
      run: |
        strip bin/libgdsion.linux.*
        chmod +x bin/libgdsion.linux.*

    - name: Prepare the binaries (macOS)
      if: ${{ env.SCONS_PLATFORM == 'macos' }}
      shell: bash
      run: |
        chmod +x bin/libgdsion.macos.*

    - name: Prepare the binaries (Windows)
      if: ${{ env.SCONS_PLATFORM == 'windows' }}
      shell: powershell
      run: |
        Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

    - name: Upload the binaries as an artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: libgdsion-${{ env.SCONS_PLATFORM }}
        path: "bin/*"
        retention-days: 14
