name: Upload GDSiON release
description: Strip and upload build artifacts.

inputs:
  sign-extension:
    description: Flag that enables the codesign routine for platforms that support it.
    default: false

  # Explicit secrets passthrough for codesign.
  apple-cert-base64:
    required: true
  apple-cert-password:
    required: true
  apple-dev-id:
    required: true
  apple-dev-app-id:
    required: true
  apple-dev-team-id:
    required: true
  apple-dev-password:
    required: true

runs:
  using: "composite"
  steps:

    # Linux-specific steps.

    - name: Prepare the binaries (Linux)
      if: ${{ env.SCONS_PLATFORM == 'linux' }}
      shell: bash
      run: |
        strip bin/libgdsion.linux.*
        chmod +x bin/libgdsion.linux.*

    # macOS-specific steps.

    - name: Prepare the binaries (macOS)
      if: ${{ env.SCONS_PLATFORM == 'macos' }}
      shell: bash
      run: |
        chmod +x bin/libgdsion.macos.*

    - name: Set up codesign (macOS)
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.sign-extension }}
      uses: ./.github/actions/sign-extension
      with:
        setup-env: true

        apple-cert-base64:   ${{ inputs.apple-cert-base64 }}
        apple-cert-password: ${{ inputs.apple-cert-password }}

    - name: Sign the binaries (macOS, debug)
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.sign-extension }}
      uses: ./.github/actions/sign-extension
      with:
        codesign: true
        directory: bin
        target-name: libgdsion.macos.template_debug.framework

        apple-dev-id:        ${{ inputs.apple-dev-id }}
        apple-dev-app-id:    ${{ inputs.apple-dev-app-id }}
        apple-dev-team-id:   ${{ inputs.apple-dev-team-id }}
        apple-dev-password:  ${{ inputs.apple-dev-password }}

    - name: Sign the binaries (macOS, release)
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.sign-extension }}
      uses: ./.github/actions/sign-extension
      with:
        codesign: true
        directory: bin
        target-name: libgdsion.macos.template_release.framework

        apple-dev-id:        ${{ inputs.apple-dev-id }}
        apple-dev-app-id:    ${{ inputs.apple-dev-app-id }}
        apple-dev-team-id:   ${{ inputs.apple-dev-team-id }}
        apple-dev-password:  ${{ inputs.apple-dev-password }}

    # Windows-specific steps.

    - name: Prepare the binaries (Windows)
      if: ${{ env.SCONS_PLATFORM == 'windows' }}
      shell: powershell
      run: |
        Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

    # Common final steps.

    - name: Upload the binaries as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgdsion-${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}
        path: "bin/*"
        retention-days: 14
