name: Upload GDSiON release
description: Upload build artifacts to GitHub.

runs:
  using: "composite"
  steps:
    - name: Upload the binaries as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: libgdsion-${{ env.SCONS_PLATFORM }}${{ env.SCONS_PLATFORM_SUFFIX }}
        path: "bin/*"
        retention-days: 14
