name: Publish GDSiON release
description: Archive build artifacts and publish them.

inputs:
  directory:
    default: "."
  path:
    default: "bin"
  platform:
    default: ""
  release-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Archive the artifact
      uses: ./.github/actions/zip-folder
      with:
        directory: ${{ inputs.directory }}
        path: ${{ inputs.path }}
        filename: libgdsion-${{ inputs.platform }}.zip

    - name: Update the release with the platform artifact
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload ${{ inputs.release-version }} ${{ inputs.directory }}/libgdsion-${{ inputs.platform }}.zip --clobber
