name: Publish GDSiON release
description: Archive build artifacts and publish them.

runs:
  using: "composite"
  steps:
    - name: Archive the artifact
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        path: bin/
        filename: libgdsion-${{ env.SCONS_PLATFORM }}.zip

    - name: Update the rolling release with the artifact
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload latest-unstable libgdsion-${{ env.SCONS_PLATFORM }}.zip --clobber
        gh release edit latest-unstable --target main

