name: Publish GDSiON release
description: Archive build artifacts and publish them.

inputs:
  directory:
    default: "."
  path:
    default: "bin"
  platform:
    default: ""

runs:
  using: "composite"
  steps:
    - name: Archive the artifact
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: zip
        directory: ${{ inputs.directory }}
        path: ${{ inputs.path }}
        filename: libgdsion-${{ inputs.platform }}.zip

    - name: Update the rolling release with the artifact
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload latest-unstable ${{ inputs.directory }}/libgdsion-${{ inputs.platform }}.zip --clobber
