name: Publish GDSiON release
description: Download build artifacts and publish them.

inputs:
  artifact-url:
    description: The URL of the uploaded artifact.

runs:
  using: "composite"
  steps:
    - name: Download the artifact
      shell: bash
      run: |
        wget -O ${{ github.workspace }}/libgdsion-${{ env.SCONS_PLATFORM }}.zip ${{ inputs.artifact-url }}

    - name: Update the rolling release with the artifact
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "Artifact stored at ${{ github.workspace }}/libgdsion-${{ env.SCONS_PLATFORM }}.zip"
        gh release upload v0.0.0 ${{ github.workspace }}/libgdsion-${{ env.SCONS_PLATFORM }}.zip --clobber

