name: Run Godot tests
description: Run a test project on the target platform.

inputs:
  project-path:
    default: "./tests"
  run-script:
    default: "./run.gd"

runs:
  using: "composite"
  steps:
    - name: Import assets, scripts, extensions
      shell: bash
      continue-on-error: true
      run: |
        godot --headless --path ${{ inputs.project-path }} --import

    - name: Run the project script
      shell: bash
      continue-on-error: true # Temporarily ignore the exit code and just continue.
      run: |
        godot --headless --path ${{ inputs.project-path }} --script ${{ inputs.run-script }} --verbose
