name: Update GitHub Release
description: Update the tag of an existing GH Release, and republish it.

inputs:
  release-version:
    required: true
  republish:
    default: false

runs:
  using: "composite"
  steps:
    - name: Update the release tag
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        git tag -d ${{ inputs.release-version }}
        git push origin :refs/tags/${{ inputs.release-version }}
        git tag ${{ inputs.release-version }} ${{ git.sha }}
        git push origin ${{ inputs.release-version }}

    - name: Republish the release
      if: ${{ inputs.republish }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release edit ${{ inputs.release-version }} --draft=false
