name: Build Extension - macOS

on:
  workflow_call:

# Make sure jobs cannot overlap.
concurrency:
  group: build-unstable-main-macos
  cancel-in-progress: true

jobs:
  build:
    name: Compile and upload macOS version
    runs-on: macos-latest
    env:
      SCONS_PLATFORM: macos

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up build cache
        uses: ./.github/actions/setup-cache
        continue-on-error: true

      - name: Install build dependencies
        uses: ./.github/actions/install-deps

      - name: Build GDSiON (release)
        uses: ./.github/actions/build-extension
        with:
          target: template_release

      - name: Build GDSiON (debug)
        uses: ./.github/actions/build-extension
        with:
          target: template_debug

      - name: Upload release
        uses: ./.github/actions/upload-extension
