name: Export Godot project
description: Export a project for the target platform.

inputs:
  platform:
    required: true
  arch:
    required: true
  preset:
    required: true
  output:
    required: true

outputs:
  path:
    value: ${{ steps.export-project-step.outputs.export-path }}

runs:
  using: "composite"
  steps:
    - name: Export project (${{ inputs.preset }})
      id: export-project-step
      shell: bash
      env:
        EXPORT_OUTPUT_PATH: ./example/export/${{ inputs.platform }}/${{ inputs.arch }}
      run: |
        godot --headless --path ./example --editor --quit
        godot --headless --path ./example --export-release "${{ inputs.preset }}" ${{ env.EXPORT_OUTPUT_PATH }}/${{ inputs.output }}
        echo "export-path=${{ env.EXPORT_OUTPUT_PATH }}" >> "$GITHUB_OUTPUT"
