name: Export Godot project
description: Export a project for the target platform.

inputs:
  platform:
    required: true
  arch:
    required: true
  preset:
    required: true
  output:
    required: true
  app-name:
    required: true

  project-path:
    default: "./example"

outputs:
  export-path:
    value: ${{ steps.export-project-step.outputs.export-path }}

runs:
  using: "composite"
  steps:
    - name: Import assets, scripts, extensions
      shell: bash
      continue-on-error: true
      run: |
        godot --headless --path ${{ inputs.project-path }} --import

    - name: Export the project (${{ inputs.preset }})
      id: export-project-step
      shell: bash
      env:
        EXPORT_OUTPUT_PATH: export/${{ inputs.platform }}/${{ inputs.arch }}
      run: |
        echo "Creating the export output folder..."
        mkdir -p ${{ inputs.project-path }}/${{ env.EXPORT_OUTPUT_PATH }}

        echo "Exporting the project..."
        godot --headless --path ${{ inputs.project-path }} --export-release "${{ inputs.preset }}" ${{ env.EXPORT_OUTPUT_PATH }}/${{ inputs.output }}
        echo "export-path=${{ inputs.project-path }}/${{ env.EXPORT_OUTPUT_PATH }}" >> "$GITHUB_OUTPUT"

    # Perform post-export steps.

    # We need the .app folder on macOS, not the zip that Godot produces.
    - name: Unzip the project (macos)
      if: ${{ inputs.platform == 'macos' }}
      shell: bash
      env:
        EXPORT_OUTPUT_PATH: export/${{ inputs.platform }}/${{ inputs.arch }}
      run: |
        cd ${{ inputs.project-path }}/${{ env.EXPORT_OUTPUT_PATH }}
        unzip ${{ inputs.output }}
        rm -f ${{ inputs.output }}
        chmod +x "${{ inputs.app-name }}/Contents/MacOS/$(basename "${{ inputs.app-name }}" .app)"
