name: Codesign GDSiON
description: Codesign and notarize extension build artifacts.

# This actions is close but slightly different to sign-godot-project. Eventually,
# they may be unified. But for now care should be applied to keep them in sync when
# it matters.

inputs:
  setup-env:
    description: Flag that enables the setup step.
    default: false
  codesign:
    description: Flag that enables the codesign step.
    default: false

  # Setup arguments.
  apple-cert-base64:
    required: true
  apple-cert-password:
    required: true

  # Codesign arguments.
  apple-dev-id:
    required: true
  apple-dev-app-id:
    required: true
  apple-dev-team-id:
    required: true
  apple-dev-password:
    required: true

  # Input/output arguments.
  directory:
    description: Path to the folder with the extension.
    required: true
  target-name:
    description: Name of the extension executable file or folder (like on macOS).
    required: true

runs:
  using: composite
  steps:
    # macOS-specific steps.

    # Setup.

    - name: Set up the signing environment (macos)
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.setup-env == 'true' }}
      shell: bash
      env:
        APPLE_CERT_BASE64:   ${{ inputs.apple-cert-base64 }}
        APPLE_CERT_PASSWORD: ${{ inputs.apple-cert-password }}
      run: $GITHUB_ACTION_PATH/macos/setup.sh

    # Codesign.

    - name: Prepare the .plist file
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.codesign == 'true' }}
      shell: bash
      env:
        RESOURCES_PATH: '${{ inputs.directory }}/${{ inputs.target-name }}.framework/Resources'
      run: |
        mkdir $RESOURCES_PATH
        sed 's/\${FRAMEWORK_NAME}/${{ inputs.target-name }}/g' $GITHUB_ACTION_PATH/macos/Info.plist > $RESOURCES_PATH/Info.plist

    - name: Sign and notarize the extension (macos)
      if: ${{ env.SCONS_PLATFORM == 'macos' && inputs.codesign == 'true' }}
      shell: bash
      env:
        APPLE_DEV_ID:       ${{ inputs.apple-dev-id }}
        APPLE_DEV_APP_ID:   ${{ inputs.apple-dev-app-id }}
        APPLE_DEV_TEAM_ID:  ${{ inputs.apple-dev-team-id }}
        APPLE_DEV_PASSWORD: ${{ inputs.apple-dev-password }}
        FRAMEWORK_PATH:     ${{ inputs.directory }}/${{ inputs.target-name }}.framework
      run: $GITHUB_ACTION_PATH/macos/sign.sh
