name: Build GDSiON extension
description: Build the exntesion with provided options.

inputs:
  target:
    description: The build configuration target (template_release, template_debug).
    default: "template_release"
  sconsflags:
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build with scons
      shell: bash
      env:
          SCONSFLAGS: ${{ inputs.sconsflags }}
      run: |
        echo "Building with flags:" platform=${{ env.SCONS_PLATFORM }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}
        scons platform=${{ env.SCONS_PLATFORM }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}

        echo "Build results:"
        ls -l bin/
        echo "Example project build results:"
        ls -l example/bin/
