name: Build GDSiON extension
description: Build the exntesion with provided options.

inputs:
  target:
    description: The build configuration target (editor, template_release, template_debug).
    default: "template_release"
  sconsflags:
    description: Additional build flags for scons.
    default: ""
  finalize-binaries:
    description: Flag that enables finalization steps, like stripping.
    default: true

runs:
  using: "composite"
  steps:
    - name: Build with scons
      shell: bash
      env:
          SCONSFLAGS: ${{ inputs.sconsflags }}
          SCONS_CACHE: ${{ github.workspace }}/.scons-cache/
          SCONS_CACHE_LIMIT: 7168
      run: |
        echo "Building with flags:" platform=${{ env.SCONS_PLATFORM }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}
        scons platform=${{ env.SCONS_PLATFORM }} target=${{ inputs.target }} ${{ env.SCONSFLAGS }}

        echo "Build results:"
        ls -l bin/
        echo "Example project build results:"
        ls -l example/bin/

    # Linux-specific post-build steps.

    - name: Prepare the binaries (Linux)
      if: ${{ env.SCONS_PLATFORM == 'linux' && inputs.finalize-binaries == 'true' }}
      shell: bash
      run: |
        strip bin/libgdsion.linux.*

    # Windows-specific post-build steps.

    - name: Prepare the binaries (Windows)
      if: ${{ env.SCONS_PLATFORM == 'windows' && inputs.finalize-binaries == 'true' }}
      shell: powershell
      run: |
        Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
