name: Build Example Project

on:
  workflow_call:

# Make sure jobs cannot overlap.
concurrency:
  group: build-unstable-example-project
  cancel-in-progress: true

jobs:
  export-publish:
    name: Export and publish the example project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download GDSiON artifacts
        uses: actions/download-artifact@v4
        with:
          path: example/bin
          merge-multiple: true

      - name: Archive the example project
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          directory: example
          filename: libgdsion-example-project.zip

      - name: Update the rolling release with the example project
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest-unstable example/libgdsion-example-project.zip --clobber
          gh release edit latest-unstable --target $(git log --format="%H" -n 1)

