name: Publish Example Project

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

# Make sure jobs cannot overlap.
concurrency:
  group: publish-${{ github.ref }}-example-project
  cancel-in-progress: true

jobs:
  publish:
    name: Package and publish the example project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download GDSiON artifacts
        uses: actions/download-artifact@v4
        with:
          path: example/bin
          pattern: libgdsion-*
          merge-multiple: true

      - name: Archive example project sources
        uses: ./.github/actions/zip-folder
        with:
          directory: example
          filename: example-project-source.zip

      - name: Download example project artifacts
        uses: actions/download-artifact@v4
        with:
          path: example/export
          pattern: example-project-*

      - name: Untar downloaded artifacts
        shell: bash
        working-directory: example/export
        run: |
          for name in ./*; do
            if [ -d "$name" ]; then
              cd "./$name"
              tar -xvf gdsion-example.tar
              rm -f gdsion-example.tar
              cd ..
            fi
          done

      - name: Archive example project exports
        uses: ./.github/actions/zip-folder
        with:
          directory: example/export
          split: true

      - name: Update the release with the example project
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ inputs.release-version }} example/example-project-source.zip --clobber
          gh release upload ${{ inputs.release-version }} example/export/*.zip --clobber

