name: Publish Example Project

on:
  workflow_call:

# Make sure jobs cannot overlap.
concurrency:
  group: publish-unstable-example-project
  cancel-in-progress: true

jobs:
  publish:
    name: Package and publish the example project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download GDSiON artifacts
        uses: actions/download-artifact@v4
        with:
          path: example/bin
          pattern: libgdsion-*
          merge-multiple: true

      - name: Archive example project sources
        uses: ./.github/actions/zip-folder
        with:
          directory: example
          filename: example-project-source.zip

      - name: Download example project artifacts
        uses: actions/download-artifact@v4
        with:
          path: example/export
          pattern: example-project-*

      - name: Archive example project exports
        uses: ./.github/actions/zip-folder
        with:
          directory: example/export
          split: true

      - name: Update the rolling release with the example project
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload latest-unstable example/example-project-source.zip --clobber
          gh release upload latest-unstable example/export/*.zip --clobber

