name: Build Extension - macOS

on:
  workflow_call:
    inputs:
      git-base-ref:
        type: string
        default: 'main'
      with-codesign:
        type: boolean
        default: false

# Make sure jobs cannot overlap.
concurrency:
  group: build-${{ github.ref }}-macos
  cancel-in-progress: true

jobs:
  build:
    name: Compile and upload macOS version
    runs-on: macos-latest
    env:
      GIT_BASE_REF: ${{ inputs.git-base-ref }}
      SCONS_PLATFORM: macos

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up build cache
        uses: ./.github/actions/setup-cache
        continue-on-error: true

      - name: Install build dependencies
        uses: ./.github/actions/install-deps

      - name: Build GDSiON (release)
        uses: ./.github/actions/build-extension
        with:
          target: template_release

      - name: Build GDSiON (debug)
        uses: ./.github/actions/build-extension
        with:
          target: template_debug

      - name: Upload release
        uses: ./.github/actions/upload-extension
        with:
          sign-extension: ${{ inputs.with-codesign }}
          apple-cert-base64:   ${{ secrets.APPLE_CERT_BASE64 }}
          apple-cert-password: ${{ secrets.APPLE_CERT_PASSWORD }}
          apple-dev-id:        ${{ secrets.APPLE_DEV_ID }}
          apple-dev-app-id:    ${{ secrets.APPLE_DEV_APP_ID }}
          apple-dev-team-id:   ${{ secrets.APPLE_DEV_TEAM_ID }}
          apple-dev-password:  ${{ secrets.APPLE_DEV_PASSWORD }}
