name: Build Extension - Linux

on:
  workflow_call:
    inputs:
      git-base-ref:
        type: string
        default: 'main'

# Make sure jobs cannot overlap.
concurrency:
  group: build-${{ github.ref }}-linux
  cancel-in-progress: true

jobs:
  build:
    name: Compile and upload Linux version
    runs-on: ubuntu-latest
    env:
      GIT_BASE_REF: ${{ inputs.git-base-ref }}
      SCONS_PLATFORM: linux

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Set up prerequisites.

      - name: Set up build cache
        uses: ./.github/actions/setup-cache
        continue-on-error: true

      - name: Install build dependencies
        uses: ./.github/actions/install-deps

      - name: Setup GCC problem matcher
        uses: ammaraskar/gcc-problem-matcher@master

      # Build all targets.

      - name: Build GDSiON (release)
        uses: ./.github/actions/build-extension
        with:
          target: template_release

      - name: Build GDSiON (debug)
        uses: ./.github/actions/build-extension
        with:
          target: template_debug

      # Upload the results.

      - name: Upload release
        uses: ./.github/actions/upload-extension
