name: Build Extension - Web

on:
  workflow_call:

# Make sure jobs cannot overlap.
concurrency:
  group: build-${{ github.ref }}-web
  cancel-in-progress: true

jobs:
  build:
    name: Compile and upload Web version
    runs-on: ubuntu-latest
    env:
      GIT_BASE_REF: 'main'
      SCONS_PLATFORM: web

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up build cache
        uses: ./.github/actions/setup-cache
        continue-on-error: true

      - name: Install build dependencies
        uses: ./.github/actions/install-deps

      - name: Build GDSiON (release)
        uses: ./.github/actions/build-extension
        with:
          target: template_release

      - name: Build GDSiON (debug)
        uses: ./.github/actions/build-extension
        with:
          target: template_debug

      - name: Upload release
        uses: ./.github/actions/upload-extension
