name: Publish Extension

on:
  workflow_call:

# Make sure jobs cannot overlap.
concurrency:
  group: publish-unstable-main
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        platform: [ linux, macos, windows, web, android ]

    name: Package and publish the extension (${{ matrix.platform }})
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download GDSiON artifacts
        id: artifact-download-step
        uses: actions/download-artifact@v4
        with:
          path: artifacts/bin
          pattern: libgdsion-${{ matrix.platform }}*
          merge-multiple: true

      - name: Publish release
        uses: ./.github/actions/publish-extension
        with:
          directory: artifacts/
          path: bin/
          platform: ${{ matrix.platform }}
